name: CI LIB_DMFT_ED test workflow 

on: push

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-QcmP:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:

#********* SETUP PART **********

# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

# QcmPlab setup
      - uses: QcmPlab/TestSetup@master
        with:
          pack-type: open



#********* BUILD PART **********

# Build SciFortran
      - name: Cloning SciFortran
        run: git clone https://github.com/QcmPlab/SciFortran.git scifor
      - name: Install SciFortran
        run: scifor/bin/ci_setup_scifor.sh

# Build LIB_DMFT_ED
      - name: Cloning LIB_DMFT_ED
        run: git clone https://github.com/QcmPlab/LIB_DMFT_ED.git LIB_DMFT_ED
      - name: Install LIB_DMFT_ED
        run: |
          source ~/.scifor_config_user
          export PKG_CONFIG_PATH=~/.pkgconfig.d
          export GLOB_INC=$( pkg-config --cflags scifor )
          export GLOB_LIB=$( pkg-config --libs   scifor  | sed  "s/;/ /g"  | sed 's/\\/  /g' )
          LIB_DMFT_ED/bin/ci_setup_dmft_ed.sh



#******** TESTING PART ********

# Testing
      - name: Building tests
        run:  |
          source ~/.scifor_config_user
          source ~/.dmft_ed_config_user
          export PKG_CONFIG_PATH=~/.pkgconfig.d
          export GLOB_INC=$( pkg-config --cflags scifor dmft_ed)
          export GLOB_LIB=$( pkg-config --libs   scifor dmft_ed | sed  "s/;/ /g"  | sed 's/\\/  /g' )
          cd LIB_DMFT_ED/test
          export TERM=xterm
          make all

      - name: Testing...
        run: |
          cd LIB_DMFT_ED/test
          make test

      - name: Install LCOV or alternatives
        if: contains( matrix.os, 'ubuntu')
        run: |
          sudo apt-get install lcov
          sudo update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc_v }} 100 \
            --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.gcc_v }} \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ matrix.gcc_v }}

      - name: Create coverage report
        if: contains( matrix.os, 'ubuntu')
        run: |
          mkdir -p ${{ env.COV_DIR }}
          lcov --capture --initial --base-directory . --directory test/ --output-file ${{ env.COV_DIR }}/coverage.base
          lcov --capture --base-directory . --directory test/ --output-file ${{ env.COV_DIR }}/coverage.capture
          lcov --add-tracefile ${{ env.COV_DIR }}/coverage.base --add-tracefile ${{ env.COV_DIR }}/coverage.capture --output-file ${{ env.COV_DIR }}/coverage.info
        env:
          COV_DIR: test/coverage

      - name: Upload coverage report to CODECOV
        if: contains( matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v3
        with:
          files: test/coverage/coverage.info
